name = "zsh"
description = "Zsh shell configuration"
config_paths = [
    "~/.zshrc",
    "~/.config/zsh",
]
include_patterns = ["*"]
exclude_patterns = []
follow_symlinks = true
backup_subdir = "packages/zsh"
created_at = "2025-06-20T16:59:27.930064657Z"
modified_at = "2025-06-20T16:59:27.930065151Z"
