# Managed by ~/.config/eww/scripts/theme.py: btop colours follow the wallpaper.
#Bashtop gruvbox (https://github.com/morhetz/gruvbox) theme
#by BachoSeven

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#FFFFFF", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#000000"

# Main text color
theme[main_fg]="#a6aecb"

# Title color for boxes
theme[title]="#cdd6f4"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#b4befe"

# Background color of selected items
theme[selected_bg]="#222229"

# Foreground color of selected items
theme[selected_fg]="#b4befe"

# Color of inactive/disabled text
theme[inactive_fg]="#7c849c"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#a6aecb"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#b4befe"

# Cpu box outline color
theme[cpu_box]="#676e9c"

# Memory/disks box outline color
theme[mem_box]="#676e9c"

# Net up/down box outline color
theme[net_box]="#676e9c"

# Processes box outline color
theme[proc_box]="#676e9c"

# Box divider line and small boxes line color
theme[div_line]="#454c62"

# Temperature graph colors
theme[temp_start]="#464b68"
theme[temp_mid]="#6f76a5"
theme[temp_end]="#ea6962"

# CPU graph colors
theme[cpu_start]="#464b68"
theme[cpu_mid]="#6f76a5"
theme[cpu_end]="#b4befe"

# Mem/Disk free meter
theme[free_start]="#464b68"
theme[free_mid]="#6f76a5"
theme[free_end]="#b4befe"

# Mem/Disk cached meter
theme[cached_start]="#464b68"
theme[cached_mid]="#6f76a5"
theme[cached_end]="#b4befe"

# Mem/Disk available meter
theme[available_start]="#464b68"
theme[available_mid]="#6f76a5"
theme[available_end]="#b4befe"

# Mem/Disk used meter
theme[used_start]="#464b68"
theme[used_mid]="#6f76a5"
theme[used_end]="#ea6962"

# Download graph colors
theme[download_start]="#464b68"
theme[download_mid]="#6f76a5"
theme[download_end]="#b4befe"

# Upload graph colors
theme[upload_start]="#464b68"
theme[upload_mid]="#6f76a5"
theme[upload_end]="#b4befe"
theme[process_start]="#464b68"
theme[process_mid]="#6f76a5"
theme[process_end]="#b4befe"
