[General]
AlwaysEnablePreviewZoom=false
FileParameterDefaultPath=/home/utsav
FolderParameterDefaultValue=/home/utsav
LogosAreVisible=true
OutputMessageMode=0
PreviewTimeout=16
SelectedFilter=

[Config]
ExpandedFolders=@Invalid()
FilterSources=${GMIC_PATH}/.gmic, ${HOME}/.gmic
FilterTranslation=false
HighDPIEnabled=false
LanguageCode=
MainWindowMaximized=false
MainWindowPosition=@Point(0 0)
MainWindowRect=@Rect(0 0 3436 1391)
NativeColorDialogs=false
NativeFileDialogs=false
NotifyIfStartupUpdateFails=true
OfficialFilterSource=EnabledWithUpdates
PanelSize0=1362
PanelSize1=682
PanelSize2=1362
PreviewEnabled=true
PreviewPosition=Right
PreviewSplitterType=2
RefreshInternetUpdate=true
ScreenGeometries="(0,0,3440,1440)"
UpdatesPeriodicityValue=720

[LastExecution]
ExitedNormally=true
HostApplicationID=1351
gmic_version=361
host_standalone\Arguments=
host_standalone\Command=
host_standalone\FilterHash=
host_standalone\FilterPath=
host_standalone\GmicStatusString=
host_standalone\InputMode=0
host_standalone\OutputMode=0
