$foreground = rgb(ddc7a1);
$background = rgb(000000);
$color0 = rgb(141517);
$color1 = rgb(ea6962);
$color2 = rgb(a9b665);
$color3 = rgb(d8a657);
$color4 = rgb(7daea3);
$color5 = rgb(d3869b);
$color6 = rgb(89b482);
$color7 = rgb(a89984);
$color8 = rgb(928374);
$color9 = rgb(ea6962);
$color10 = rgb(a9b665);
$color11 = rgb(d8a657);
$color12 = rgb(7daea3);
$color13 = rgb(d3869b);
$color14 = rgb(89b482);
$color15 = rgb(ddc7a1);

