# Profiling
# zmodload zsh/zprof
# shellcheck disable=SC2034,SC2086,SC2296,SC2016,SC1090,SC1091,SC1094,SC2154

# Enable history
HISTSIZE=100000
SAVEHIST=$HISTSIZE
HISTFILE=${HOME}/.zsh_history
HISTDUP=erase

setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups
setopt inc_append_history
setopt hist_reduce_blanks

# Enable auto completion
#setopt auto_menu
#setopt auto_list
#setopt auto_param_keys
#setopt auto_param_slash
#setopt auto_remove_slash
#setopt autocd
#setopt auto_pushd

setopt correct

autoload -Uz compinit && compinit
zstyle :compinstall filename '${HOME}/.zshrc'
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
# disable sort when completing `git checkout`
zstyle ':completion:*:git-checkout:*' sort false
# set descriptions format to enable group support
# NOTE: don't use escape sequences here, fzf-tab will ignore them
zstyle ':completion:*:descriptions' format '[%d]'
# set list-colors to enable filename colorizing
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
# force zsh not to show completion menu, which allows fzf-tab to capture the unambiguous prefix
zstyle ':completion:*' menu no
# defer fzf-tab initialization until the first completion
zstyle ':fzf-tab:*' auto-insert false
# preview directory's content with eza when completing cd
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -1 --color=always $realpath'
# switch group using `<` and `>`
zstyle ':fzf-tab:*' switch-group '<' '>'

# Enable aliases
setopt aliases

[[ -f ${HOME}/.config/zsh/aliases.zsh ]] && source ${HOME}/.config/zsh/aliases.zsh

# Key bindings
bindkey -v
bindkey '^[[1;5C' forward-word
bindkey '^[[1;5D' backward-word
bindkey '^[[F' end-of-line
bindkey '^[[H' beginning-of-line
bindkey '^[[3~' delete-word
bindkey '^[[2~' kill-line
bindkey '^[[3~' delete-char
bindkey -M viins "^E" end-of-line
bindkey -M viins "^A" beginning-of-line
bindkey -M viins "^P" history-search-backward
bindkey -M viins "^N" history-search-forward

command -v zoxide >/dev/null 2>&1 && eval "$(zoxide init zsh)"

### Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
	print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
	command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
	command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" &&
		print -P "%F{33} %F{34}Installation successful.%f%b" ||
		print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
	zdharma-continuum/zinit-annex-as-monitor \
	zdharma-continuum/zinit-annex-bin-gem-node \
	zdharma-continuum/zinit-annex-patch-dl \
	zdharma-continuum/zinit-annex-rust

zinit light z-shell/F-Sy-H
zinit light zsh-users/zsh-autosuggestions
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-history-substring-search
zinit light zsh-users/zsh-syntax-highlighting
zinit light Aloxaf/fzf-tab

# zsh-autosuggestions

# Disable automatic widget re-binding on each precmd. This can be set when
# zsh-users/zsh-autosuggestions is the last module in your ~/.zimrc.
ZSH_AUTOSUGGEST_MANUAL_REBIND=1
# Customize the style that the suggestions are shown with.
# See https://github.com/zsh-users/zsh-autosuggestions/blob/master/README.md#suggestion-highlight-style
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='bold'

# zsh-syntax-highlighting

# Set what highlighters will be used.
# See https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters.md
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

# Customize the main highlighter styles.
# See https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/main.md#how-to-tweak-it
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[comment]='fg=242'

# Cargo environment
if [ -f ${HOME}/.cargo/env ]; then
	source ${HOME}/.cargo/env
else
	[[ -d ${HOME}/.cargo/bin ]] && export PATH="${HOME}/.cargo/bin:${PATH}"
fi

# Rust
! command -v rustc >/dev/null 2>&1 && curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable

# Python binaries
[[ -d ${HOME}/.local/bin ]] && export PATH="${HOME}/.local/bin":${PATH}

# Mason binaries
[[ -d ${HOME}/.local/share/nvim/mason/bin ]] && export PATH="${HOME}/.local/share/nvim/mason/bin":${PATH}

# Gitlint
[[ -f ${HOME}/.gitlint ]] && export GITLINT_CONFIG=${HOME}/.gitlint

# Edit command line
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey '^X^E' edit-command-line
fpath+=${ZDOTDIR:-${HOME}}/.zsh_functions

# Set default editor
command -v nvim >/dev/null 2>&1 && export EDITOR=nvim

# FZF
if [ ! -f ${HOME}/.fzf.zsh ]; then
	clone_repo_with_progress "https://github.com/junegunn/fzf" ${HOME}/.fzf
	${HOME}/.fzf/install
fi
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# bun completions
[[ -s "${HOME}/.bun/_bun" ]] && source "${HOME}/.bun/_bun"

# bun
[[ -d $HOME/.bun ]] && export BUN_INSTALL="$HOME/.bun" && export PATH="$BUN_INSTALL/bin:$PATH"

# Local binaries
[[ -d $HOME/.local/bin ]] && export PATH=$HOME/.local/bin:$PATH

# Pyenv
#if [ -d ${HOME}/.pyenv ]; then
#	export PYENV_ROOT="$HOME/.pyenv"
#	[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
#	eval "$(pyenv init -)"
#	eval "$(pyenv virtualenv-init -)"
#fi

# Set QT theme
command -v qt6ct >/dev/null && export QT_QPA_PLATFORMTHEME="qt6ct"

# Pywal
# if command -v wal >/dev/null; then
# 	(cat ${HOME}/.cache/wal/sequences &)
# fi

# Set newt colors
[[ -f $HOME/.newt-colors ]] && export NEWT_COLORS_FILE=${HOME}/.newt-colors

# Enable console cursor
function cursor_tty() {
	sudo su -c "setterm -cursor on >> /etc/issue"
}

# Theme
! command -v starship >/dev/null 2>&1 && curl -sS https://starship.rs/install.sh | sh
export STARSHIP_CONFIG=${HOME}/.config/starship.toml
eval "$(starship init zsh)"

get_latest_wallpaper() {
	local log_file="$HOME/.cache/wallpaper_changer.log"
	local regex="^(Wallpaper set using|Animating GIF wallpaper): "

	if [[ -f "$log_file" ]]; then
		# awk -F': ' '$0 ~ "'"$regex"'" {print $2} END {if (NR) print $0; else print "No wallpaper set yet."}' "$log_file"

		awk '"'"$regex"'" {latest=$0} END {if (latest) print latest; else print "No wallpaper set yet."}' "$log_file" | awk -F': ' '{print $2}'
	else
		echo "Log file not found: $log_file"
	fi
}

# Fzf integration to kill a process by name
kill_process() {
    local process_name="$1"
    if [[ -z "$process_name" ]]; then
        echo "Usage: kill_process <partial-process-name>"
        return 1
    fi

    # Get the list of processes matching the partial name
    local process_list
    # shellcheck disable=SC2009
    process_list=$(ps -eo pid,command | grep -i "$process_name" | grep -v grep)

    if [[ -z "$process_list" ]]; then
        echo "No matching processes found for: $process_name"
        return 1
    fi

    # Use fzf to select a process
    local selected_process
    selected_process=$(echo "$process_list" | fzf --ansi --preview 'echo {}' --height ~20%)

    if [[ -z "$selected_process" ]]; then
        echo "No process selected."
        return 1
    fi

    # Extract the PID (2nd field in `ps -ef` output)
    local pid
    pid=$(echo "$selected_process" | awk '{print $2}')

    # Confirm and kill the process
    echo "Selected process:"
    echo "$selected_process"
    echo -n "Are you sure you want to kill this process? (y/N): "
    read -r confirm

    if [[ "$confirm" =~ ^[Yy]$ ]]; then
        if kill -9 "$pid" 2>/dev/null; then
            echo "Process $pid killed successfully."
        else
            echo "Failed to kill process $pid. You might need additional permissions."
        fi
    else
        echo "Process not killed."
    fi
}

# zprof
