fps
frametime
frame_timing
cpu_stats
cpu_temp
cpu_load_change
gpu_stats
gpu_temp
gpu_mem_clock
gpu_core_clock
gpu_name
vram
ram
fps_limit=0
toggle_hud=Shift_R+F12
toggle_hud_position=Shift_R+F11
reload_cfg=Shift_L+F4
position=top-left
font_size=20
