[Interface]
buttonbox_layout=0
cursor_flash_time=1000
underline_shortcut=1
activate_item_on_single_click=1
stylesheets=@Invalid()
dialog_buttons_have_icons=1
double_click_interval=400
toolbutton_style=4
wheel_scroll_lines=3
gui_effects=@Invalid()
menus_have_icons=true
keyboard_scheme=2
show_shortcuts_in_context_menus=true

[Appearance]
custom_palette=true
cosmic_qt_version=1
color_scheme_path=/home/utsav/.local/share/color-schemes/EwwDynamic.colors
style=Fusion
icon_theme=Gruvbox-Plus-Dark
standard_dialogs=xdgdesktopportal

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\b\xf\0\0\x2\xb8\0\0\0\0\0\0\0\0\0\0\b\xf\0\0\x2\xb8\0\0\0\0\0\0\0\0\rp\0\0\0\0\0\0\0\0\0\0\b\xf\0\0\x2\xb8)

[Fonts]
general="AdwaitaMono Nerd Font,12,-1,5,50,0,0,0,0,0,Regular"
fixed="AdwaitaMono Nerd Font,12,-1,5,50,0,0,0,0,0,Regular"
